/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ResearchLab;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ResearchLabOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JPanel;

/**
 *
 * @author Yash
 */
public class ResearchLabAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResearchLabAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem business;
    UserAccount account;
    ResearchLabOrganization organization;
    public ResearchLabAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem business, UserAccount account, ResearchLabOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business = business;
        this.organization=organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCreateVaccine = new javax.swing.JButton();
        btnViewVaccine = new javax.swing.JButton();
        btnManageDiseaseList = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Research Lab Admin");

        jLabel2.setBackground(new java.awt.Color(102, 217, 255));
        jLabel2.setText("Enterprise:");

        jLabel3.setText("<value>");

        btnCreateVaccine.setBackground(new java.awt.Color(102, 217, 255));
        btnCreateVaccine.setText("Create New Vaccine");
        btnCreateVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVaccineActionPerformed(evt);
            }
        });

        btnViewVaccine.setBackground(new java.awt.Color(102, 217, 255));
        btnViewVaccine.setText("Available/Current Vaccines");
        btnViewVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVaccineActionPerformed(evt);
            }
        });

        btnManageDiseaseList.setBackground(new java.awt.Color(102, 217, 255));
        btnManageDiseaseList.setText("Manage Disease");
        btnManageDiseaseList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDiseaseListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(btnCreateVaccine, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(btnViewVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageDiseaseList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(526, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addComponent(btnManageDiseaseList, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVaccineActionPerformed
        // TODO add your handling code here:
        CreateNewVaccineJPanel createNewVaccineJPanel = new CreateNewVaccineJPanel(userProcessContainer, business);
        userProcessContainer.add("createNewVaccineJPanel", createNewVaccineJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateVaccineActionPerformed

    private void btnViewVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVaccineActionPerformed
        // TODO add your handling code here:
        ManageVaccineListJPanel manageVaccineListJPanel = new ManageVaccineListJPanel(userProcessContainer, business, account,organization,enterprise);
        userProcessContainer.add("manageVaccineListJPanel", manageVaccineListJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);	

    }//GEN-LAST:event_btnViewVaccineActionPerformed

    private void btnManageDiseaseListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDiseaseListActionPerformed
        // TODO add your handling code here:
        ManageDiseaseListJPanel manageDiseaseListJPanel = new ManageDiseaseListJPanel(userProcessContainer, business);
        userProcessContainer.add("manageDiseaseListJPanel", manageDiseaseListJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);	

    }//GEN-LAST:event_btnManageDiseaseListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateVaccine;
    private javax.swing.JButton btnManageDiseaseList;
    private javax.swing.JButton btnViewVaccine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
