/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Sponsor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NGOWorkRequest;
import Business.WorkQueue.SponsorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shubhisharma
 */
public class SponsorManageNgoRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SponsorManageNgoRequestJPanel
     */
        
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem business;
    UserAccount account;

    public SponsorManageNgoRequestJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem business, UserAccount account) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.enterprise = enterprise;
       this.business = business;
       this.account = account;
      populateWorkQueueTable();
    }
    
      public void populateWorkQueueTable(){
         DefaultTableModel model = (DefaultTableModel) tblSponsorManageRequestNgo.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest work : business.getWorkQueue().getWorkRequestList()){
           if(work instanceof SponsorWorkRequest){ 
            Object[] row = new Object[5];
            row[0] = ((SponsorWorkRequest) work).getRequestedAmount();
            row[1] = ((SponsorWorkRequest) work).getRequestedDate();
            row[2] = ((SponsorWorkRequest) work).getRequestedTime();
            row[3] = ((SponsorWorkRequest) work).getVenue();
            row[4] = work;
            model.addRow(row);
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSponsorManageRequestNgo = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnApproveReqSponsor = new javax.swing.JButton();
        btnRejectReqSponsor = new javax.swing.JButton();
        btnDeleteRequest = new javax.swing.JButton();
        btnAssignToMe = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Manage Request From NGO");

        jLabel2.setBackground(new java.awt.Color(102, 217, 255));
        jLabel2.setText("Purpose :");

        jLabel3.setText("Blood Donation Camp");

        tblSponsorManageRequestNgo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Requested Amount", "Date of requirement", "Time of requirement", "Venue", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSponsorManageRequestNgo);
        if (tblSponsorManageRequestNgo.getColumnModel().getColumnCount() > 0) {
            tblSponsorManageRequestNgo.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel4.setText("Request for Sponsorship");

        btnApproveReqSponsor.setBackground(new java.awt.Color(102, 217, 255));
        btnApproveReqSponsor.setText("Approve Request");
        btnApproveReqSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveReqSponsorActionPerformed(evt);
            }
        });

        btnRejectReqSponsor.setBackground(new java.awt.Color(102, 217, 255));
        btnRejectReqSponsor.setText("Reject Request");
        btnRejectReqSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectReqSponsorActionPerformed(evt);
            }
        });

        btnDeleteRequest.setBackground(new java.awt.Color(102, 217, 255));
        btnDeleteRequest.setText("Delete Request");
        btnDeleteRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRequestActionPerformed(evt);
            }
        });

        btnAssignToMe.setBackground(new java.awt.Color(102, 217, 255));
        btnAssignToMe.setText("Assign to me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAssignToMe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteRequest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApproveReqSponsor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRejectReqSponsor)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRejectReqSponsor)
                    .addComponent(btnApproveReqSponsor)
                    .addComponent(btnDeleteRequest)
                    .addComponent(btnAssignToMe))
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
          int selectedRow= tblSponsorManageRequestNgo.getSelectedRow();
         if(selectedRow<0){
             JOptionPane.showMessageDialog(null, "Please select the row to assign the Request", "Warning", JOptionPane.WARNING_MESSAGE);
      }
        else{
             
         SponsorWorkRequest p=(SponsorWorkRequest) tblSponsorManageRequestNgo.getValueAt(selectedRow, 4);

         p.setStatus("Pending");
         p.setReceiver(account);
         
        populateWorkQueueTable();
       
         }
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnDeleteRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRequestActionPerformed
        // TODO add your handling code here:
          int selectedRow= tblSponsorManageRequestNgo.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select the row to delete the request", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{

            WorkRequest p=(WorkRequest) tblSponsorManageRequestNgo.getValueAt(selectedRow, 4);

           // s.getWorkQueue().getWorkRequestList().remove(p);
            //organization.getWorkQueue().getWorkRequestList().remove(p);
            account.getWorkQueue().getWorkRequestList().remove(p);
            business.getWorkQueue().getWorkRequestList().remove(p);
            enterprise.getWorkQueue().getWorkRequestList().remove(p);
            
            JOptionPane.showMessageDialog(null, "You have successfully deleted the request");
            populateWorkQueueTable();
        }
    }//GEN-LAST:event_btnDeleteRequestActionPerformed

    private void btnApproveReqSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveReqSponsorActionPerformed
        // TODO add your handling code here:
        int selectedRow= tblSponsorManageRequestNgo.getSelectedRow();
         if(selectedRow<0){
             JOptionPane.showMessageDialog(null, "Please select the row to approve the Request", "Warning", JOptionPane.WARNING_MESSAGE);
      }
        else{
             
             SponsorWorkRequest p=(SponsorWorkRequest) tblSponsorManageRequestNgo.getValueAt(selectedRow, 4);
             //if (p.getStatus().equalsIgnoreCase("Pending")) {
                if(p.getStatus().equalsIgnoreCase("Rejected")){
                 JOptionPane.showMessageDialog(null, "Cannot Approve the Rejected request", "Warning", JOptionPane.WARNING_MESSAGE);    
                 }else if(p.getStatus().equalsIgnoreCase("Approved")){
                  JOptionPane.showMessageDialog(null, "Cannot Approve the request 2 times", "Warning", JOptionPane.WARNING_MESSAGE);   
                 }else {
                    if (p.getStatus().equalsIgnoreCase("Pending")) {
                        p.setStatus("Approved");
                        p.setReceiver(account);
                }else{
                 JOptionPane.showMessageDialog(null, "Please assign first");
                }
           
                }
                 populateWorkQueueTable();
         }
    }//GEN-LAST:event_btnApproveReqSponsorActionPerformed

    private void btnRejectReqSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectReqSponsorActionPerformed
        // TODO add your handling code here:
         int selectedRow= tblSponsorManageRequestNgo.getSelectedRow();
         if(selectedRow<0){
             JOptionPane.showMessageDialog(null, "Please select the row to reject the Request", "Warning", JOptionPane.WARNING_MESSAGE);
      }
        else{
             
         SponsorWorkRequest p=(SponsorWorkRequest) tblSponsorManageRequestNgo.getValueAt(selectedRow, 4);
            if(p.getStatus().equalsIgnoreCase("Approved")){
                 JOptionPane.showMessageDialog(null, "Cannot Reject the Approved request", "Warning", JOptionPane.WARNING_MESSAGE);
             }else if(p.getStatus().equalsIgnoreCase("Rejected")){
                 
                 JOptionPane.showMessageDialog(null, "Cannot Reject the request 2 times", "Warning", JOptionPane.WARNING_MESSAGE);
             }else{
                if (p.getStatus().equalsIgnoreCase("Pending")) {
                    p.setStatus("Rejected");
                    p.setReceiver(account);
                 }else{
                 JOptionPane.showMessageDialog(null, "Please assign first");
              }
            }
            populateWorkQueueTable();
         }
    }//GEN-LAST:event_btnRejectReqSponsorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveReqSponsor;
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnDeleteRequest;
    private javax.swing.JButton btnRejectReqSponsor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSponsorManageRequestNgo;
    // End of variables declaration//GEN-END:variables
}
