/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CDC;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.WorkQueue.CDCWorkRequest;
import Business.WorkQueue.ResearchLabWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */
public class CDCManageLabRequestJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer; 
    EcoSystem business;
    Enterprise enterprise;
    /**
     * Creates new form CDCManageLabRequestJPanel
     */
    CDCManageLabRequestJPanel(JPanel userProcessContainer, EcoSystem business,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.enterprise = enterprise;
        populateVaccineRequestTable();
        
    }
    public void populateVaccineRequestTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblViewVaccine.getModel();
        model.setRowCount(0);
        System.out.println("business");
        System.out.println(business);
        for (WorkRequest work : business.getWorkQueue().getWorkRequestList())
        {
            if(work instanceof ResearchLabWorkRequest)
            {
                Object[] row = new Object[4];
                row[0] = work.getVaccine().getVaccineName();
                row[1] = work.getVaccine().getVaccineId();
                row[2] = work.getVaccine().getDisease();
                row[3] = work;
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnApproveRequest = new javax.swing.JButton();
        btnRejectRequest = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewVaccine = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("CDC Manage Lab Request");

        btnApproveRequest.setBackground(new java.awt.Color(102, 217, 255));
        btnApproveRequest.setText("Approve Request");
        btnApproveRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveRequestActionPerformed(evt);
            }
        });

        btnRejectRequest.setBackground(new java.awt.Color(102, 217, 255));
        btnRejectRequest.setText("Reject Request");
        btnRejectRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectRequestActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 217, 255));
        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblViewVaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Name", "Vaccine ID", "Disease", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewVaccine);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnApproveRequest)
                        .addGap(18, 18, 18)
                        .addComponent(btnRejectRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApproveRequest)
                    .addComponent(btnRejectRequest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRejectRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblViewVaccine.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null, "Please select any row to reject the request");
        }
        else
        {
            ResearchLabWorkRequest q = (ResearchLabWorkRequest)tblViewVaccine.getValueAt(selectedRow, 3);
            if(q.getStatus().equalsIgnoreCase("Approved"))
            {
                JOptionPane.showMessageDialog(null, "Cannot reject approved request");
            }
            else
            {
                if(q.getStatus().equalsIgnoreCase("Pending"))
                {
                    q.setStatus("Rejected");
                    //q.setReceiver(account);
                }
            }
        }
        populateVaccineRequestTable();
    }//GEN-LAST:event_btnRejectRequestActionPerformed

    private void btnApproveRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblViewVaccine.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null, "Please select the row to approve request");
        }
        else
        {
            ResearchLabWorkRequest p = (ResearchLabWorkRequest)tblViewVaccine.getValueAt(selectedRow, 3);
            if(p.getStatus().equalsIgnoreCase("Rejected"))
            {
                JOptionPane.showConfirmDialog(null, "Cannot approve rejected request");
            }
            else
            {
                 p.setStatus("Approved");
                //p.setReceiver(account);
                p.getVaccine().setFlag(true);
            }
        }
        populateVaccineRequestTable();
    }//GEN-LAST:event_btnApproveRequestActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveRequest;
    private javax.swing.JButton btnRejectRequest;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewVaccine;
    // End of variables declaration//GEN-END:variables
}
