/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airplane;
import Business.AirplaneCatalog;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */
public class CreateAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirplaneJPanel
     */
    private AirplaneCatalog aircat;
    public CreateAirplaneJPanel(AirplaneCatalog aircat) {
        initComponents();
        this.aircat = aircat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCreateSrNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCreateModelNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCreateManufacturer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCreateManYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCreateNoOfSeats = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCreateAirLineName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCreateAirport = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCreateAvailable = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCreateCertificateExpired = new javax.swing.JTextField();
        btnCreateAirplane = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CREATE NEW AIRPLANE:");

        jLabel2.setText("Serial Number:");

        txtCreateSrNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCreateSrNoKeyPressed(evt);
            }
        });

        jLabel3.setText("Model Number:");

        jLabel4.setText("Manufacturer:");

        jLabel5.setText("Manufacture Year:");

        txtCreateManYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCreateManYearKeyPressed(evt);
            }
        });

        jLabel6.setText("Number Of Seats:");

        txtCreateNoOfSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCreateNoOfSeatsKeyPressed(evt);
            }
        });

        jLabel7.setText("Air Line Name:");

        jLabel8.setText("Air Port Name:");

        jLabel9.setText("Availabe (Y/N):");

        txtCreateAvailable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCreateAvailableKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCreateAvailableKeyTyped(evt);
            }
        });

        jLabel10.setText("Maintanence Certificate (Y/N):");

        txtCreateCertificateExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateCertificateExpiredActionPerformed(evt);
            }
        });
        txtCreateCertificateExpired.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCreateCertificateExpiredKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCreateCertificateExpiredKeyTyped(evt);
            }
        });

        btnCreateAirplane.setText("CREATE");
        btnCreateAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirplaneActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Please Enter Only Numbers");

        jLabel12.setForeground(new java.awt.Color(255, 51, 0));
        jLabel12.setText("Please Enter Only Numbers");

        jLabel13.setForeground(new java.awt.Color(255, 51, 0));
        jLabel13.setText("Please Enter Only Numbers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 181, Short.MAX_VALUE)
                                .addComponent(btnCreateAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCreateModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCreateManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCreateAirLineName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCreateAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCreateCertificateExpired, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCreateAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCreateSrNo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCreateManYear, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCreateNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateSrNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCreateModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreateManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCreateManYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtCreateAirLineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCreateAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCreateNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCreateAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreateCertificateExpired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnCreateAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCreateCertificateExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateCertificateExpiredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateCertificateExpiredActionPerformed

    private void btnCreateAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirplaneActionPerformed
        // TODO add your handling code here:
       
        Airplane user =  aircat.addUserAirplane();   
      
       int serialNo = Integer.parseInt(txtCreateSrNo.getText());
       user.setSerialNo(serialNo);
        
       String modelNo = txtCreateModelNo.getText();
       user.setModelNo(modelNo);
        
        String manufact = txtCreateManufacturer.getText();
        user.setManufacturedBy(manufact);
        
        int manyear = Integer.parseInt(txtCreateManYear.getText());
        user.setManifactureYear(manyear);
        
        int seats = Integer.parseInt(txtCreateNoOfSeats.getText());
        user.setNumberOfSeats(seats);
       
        String airline = txtCreateAirLineName.getText();
        user.setAirlineName(airline);
        
        String airport = txtCreateAirport.getText();
        user.setAirport(airport);
       
        
        String availabe = txtCreateAvailable.getText();
       user.setAvailabe(availabe);
        
        
        String maintCert = txtCreateCertificateExpired.getText();
        user.setCertificateExpired(maintCert);
        
        JOptionPane.showMessageDialog(null, "Airplane Created Successfully!");
        
        txtCreateSrNo.setText("");
        txtCreateModelNo.setText("");
        txtCreateManufacturer.setText("");
        txtCreateManYear.setText("");
        txtCreateNoOfSeats.setText("");
        txtCreateAirLineName.setText("");
        txtCreateAirport.setText("");
        txtCreateAvailable.setText("");
        txtCreateCertificateExpired.setText("");
    }//GEN-LAST:event_btnCreateAirplaneActionPerformed

    private void txtCreateSrNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreateSrNoKeyPressed
       // TODO add your handling code here:
       int key = evt.getKeyCode();
       if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||(key==KeyEvent.VK_BACK_SPACE))
       {
       txtCreateSrNo.setEditable(true);
       }
       else
       {
       txtCreateSrNo.setEditable(false);
       }
    }//GEN-LAST:event_txtCreateSrNoKeyPressed

    private void txtCreateManYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreateManYearKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
       if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||(key==KeyEvent.VK_BACK_SPACE))
       {
       txtCreateManYear.setEditable(true);
       }
       else
       {
       txtCreateManYear.setEditable(false);
       }
    }//GEN-LAST:event_txtCreateManYearKeyPressed

    private void txtCreateAvailableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreateAvailableKeyTyped
        // TODO add your handling code here:
      
        if (txtCreateAvailable.getText().length() >= 1 ) // limit textfield to 1 character
            txtCreateAvailable.setEditable(false);
        else
        txtCreateAvailable.setEditable(true);
    
    }//GEN-LAST:event_txtCreateAvailableKeyTyped

    private void txtCreateAvailableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreateAvailableKeyPressed
        // TODO add your handling code here:
       int key = evt.getKeyCode();
       if((key==KeyEvent.VK_Y)||(key==evt.VK_N)||(key==KeyEvent.VK_BACK_SPACE))
       {
       txtCreateAvailable.setEditable(true);
       }
       else
       {
       txtCreateAvailable.setEditable(false);
       }
    }//GEN-LAST:event_txtCreateAvailableKeyPressed

    private void txtCreateCertificateExpiredKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreateCertificateExpiredKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
       if((key==KeyEvent.VK_Y)||(key==evt.VK_N)||(key==KeyEvent.VK_BACK_SPACE))
       {
       txtCreateCertificateExpired.setEditable(true);
       }
       else
       {
       txtCreateCertificateExpired.setEditable(false);
       }
    }//GEN-LAST:event_txtCreateCertificateExpiredKeyPressed

    private void txtCreateCertificateExpiredKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreateCertificateExpiredKeyTyped
        // TODO add your handling code here:
         if (txtCreateCertificateExpired.getText().length() >= 1 ) // limit textfield to 1 character
            txtCreateCertificateExpired.setEditable(false);
        else
        txtCreateCertificateExpired.setEditable(true);
    }//GEN-LAST:event_txtCreateCertificateExpiredKeyTyped

    private void txtCreateNoOfSeatsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreateNoOfSeatsKeyPressed
        // TODO add your handling code here:
         int key = evt.getKeyCode();
       if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||(key==KeyEvent.VK_BACK_SPACE))
       {
       txtCreateNoOfSeats.setEditable(true);
       }
       else
       {
       txtCreateNoOfSeats.setEditable(false);
       }
    }//GEN-LAST:event_txtCreateNoOfSeatsKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAirplane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCreateAirLineName;
    private javax.swing.JTextField txtCreateAirport;
    private javax.swing.JTextField txtCreateAvailable;
    private javax.swing.JTextField txtCreateCertificateExpired;
    private javax.swing.JTextField txtCreateManYear;
    private javax.swing.JTextField txtCreateManufacturer;
    private javax.swing.JTextField txtCreateModelNo;
    private javax.swing.JTextField txtCreateNoOfSeats;
    private javax.swing.JTextField txtCreateSrNo;
    // End of variables declaration//GEN-END:variables
}
