/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airplane;
import Business.AirplaneCatalog;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */
public class Qt5JPanel extends javax.swing.JPanel {

    /**
     * Creates new form Qt5JPanel
     */

    private AirplaneCatalog aircat;
    Qt5JPanel(AirplaneCatalog aircat) {
        initComponents();
        this.aircat = aircat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQt5 = new javax.swing.JLabel();
        lblMinseats = new javax.swing.JLabel();
        lblMaxSeats = new javax.swing.JLabel();
        txtMinSeats = new javax.swing.JTextField();
        txtMaxSeats = new javax.swing.JTextField();
        btnSearchBySeats = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQt5 = new javax.swing.JTable();

        lblQt5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQt5.setText("Search Airplane By Seats:");

        lblMinseats.setText("Enter Minimum Seats:");

        lblMaxSeats.setText("Enter Maximum Seats:");

        txtMinSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMinSeatsKeyPressed(evt);
            }
        });

        txtMaxSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaxSeatsKeyPressed(evt);
            }
        });

        btnSearchBySeats.setText("Search");
        btnSearchBySeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBySeatsActionPerformed(evt);
            }
        });

        tblQt5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Air Line Name", "Model Number", "Manufacturer", "Airport", "Number Of Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblQt5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblQt5, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(btnSearchBySeats))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblMinseats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(lblMaxSeats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQt5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinseats)
                    .addComponent(lblMaxSeats)
                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearchBySeats)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchBySeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBySeatsActionPerformed
        // TODO add your handling code here:
        boolean record = false;
        int maxSeats = Integer.parseInt(txtMaxSeats.getText());
        int minSeats = Integer.parseInt(txtMinSeats.getText());
        DefaultTableModel dtm = (DefaultTableModel)tblQt5.getModel();
            dtm.setRowCount(0);
            for(Airplane p :aircat.getAirplaneCatalog())
            {
                if(p.getAvailabe().equalsIgnoreCase("Y"))
                {
                    if(p.getNumberOfSeats()>=minSeats && p.getNumberOfSeats()<=maxSeats)
                    {
                Object[] row = new Object[5];
                row[0] = p.getAirlineName();
                row[1] = p.getModelNo();
                row[2] = p.getManufacturedBy();
                row[3] = p.getAirport();
                row[4] = p.getNumberOfSeats();
                dtm.addRow(row);
                record = true;
                    }
                }
            }
            if(!record)
            {
            JOptionPane.showMessageDialog(null, "Record not found");
            }
            
    }//GEN-LAST:event_btnSearchBySeatsActionPerformed

    private void txtMinSeatsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinSeatsKeyPressed
        // TODO add your handling code here:
         int key = evt.getKeyCode();
       if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||(key==KeyEvent.VK_BACK_SPACE))
       {
       txtMinSeats.setEditable(true);
       }
       else
       {
       txtMinSeats.setEditable(false);
       }
    }//GEN-LAST:event_txtMinSeatsKeyPressed

    private void txtMaxSeatsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxSeatsKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||(key==KeyEvent.VK_BACK_SPACE))
       {
       txtMaxSeats.setEditable(true);
       }
       else
       {
       txtMaxSeats.setEditable(false);
       }
    }//GEN-LAST:event_txtMaxSeatsKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchBySeats;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaxSeats;
    private javax.swing.JLabel lblMinseats;
    private javax.swing.JLabel lblQt5;
    private javax.swing.JTable tblQt5;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMinSeats;
    // End of variables declaration//GEN-END:variables
}
