/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airplane;
import Business.AirplaneCatalog;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */
public class Qt6JPanel extends javax.swing.JPanel {

    /**
     * Creates new form Qt6JPanel
     */
 
    private AirplaneCatalog aircat;
    Qt6JPanel(AirplaneCatalog aircat) {
        initComponents();
        this.aircat = aircat;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQt6 = new javax.swing.JLabel();
        lblSerialNo = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        btnSearchBySerialNo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblqt6 = new javax.swing.JTable();

        lblQt6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQt6.setText("Find Airplane By Serial Number:");

        lblSerialNo.setText("Enter Serial Number:");

        txtSerialNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSerialNoKeyPressed(evt);
            }
        });

        btnSearchBySerialNo.setText("Search");
        btnSearchBySerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBySerialNoActionPerformed(evt);
            }
        });

        tblqt6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline", "Model Number", "Manufacturer", "Manufacture Year", "Number Of Seats", "Airport", "Availablity", "Certficate Expired"
            }
        ));
        jScrollPane1.setViewportView(tblqt6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSerialNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnSearchBySerialNo))
                    .addComponent(lblQt6, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(383, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQt6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNo)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchBySerialNo))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchBySerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBySerialNoActionPerformed
        // TODO add your handling code here:
        boolean record = false;
        int serialNo = Integer.parseInt(txtSerialNo.getText());
        DefaultTableModel dtm = (DefaultTableModel)tblqt6.getModel();
            dtm.setRowCount(0);
            for(Airplane p:aircat.getAirplaneCatalog())
            {
                if((p.getSerialNo()==serialNo))
                {
                Object[] col = new Object[8];
                col[0] = p.getAirlineName();
                col[1] = p.getModelNo();
                col[2] = p.getManufacturedBy();
                col[3] = p.getManifactureYear();
                col[4] = p.getNumberOfSeats();
                col[5] = p.getAirport();
                col[6] = p.getAvailabe();
                col[7] = p.getCertificateExpired();
                dtm.addRow(col);
                record = true;
                }
                
            }
            if(!record)
            {
            JOptionPane.showMessageDialog(null, "Record not found");
            }
    }//GEN-LAST:event_btnSearchBySerialNoActionPerformed

    private void txtSerialNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNoKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||(key==KeyEvent.VK_BACK_SPACE))
       {
       txtSerialNo.setEditable(true);
       }
       else
       {
       txtSerialNo.setEditable(false);
       }
    }//GEN-LAST:event_txtSerialNoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchBySerialNo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQt6;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JTable tblqt6;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables
}
