/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airplane;
import Business.AirplaneCatalog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */
public class Qt7JPanel extends javax.swing.JPanel {

    /**
     * Creates new form Qt7JPanel
     */
  
    private AirplaneCatalog aircat;
    Qt7JPanel(AirplaneCatalog aircat) {
        initComponents();
        this.aircat = aircat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQt7 = new javax.swing.JLabel();
        lblModelNo = new javax.swing.JLabel();
        txtModelNo = new javax.swing.JTextField();
        btnSearchByModelNo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQt7 = new javax.swing.JTable();

        lblQt7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQt7.setText("List of Airplanes by Model Number:");

        lblModelNo.setText("Enter Model Number:");

        btnSearchByModelNo.setText("Search");
        btnSearchByModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByModelNoActionPerformed(evt);
            }
        });

        tblQt7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline", "Manufacturer", "Manufacture Year", "Number Of Seats", "Airport", "Availablity", "Certficate Expired"
            }
        ));
        jScrollPane1.setViewportView(tblQt7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQt7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnSearchByModelNo)))
                .addContainerGap(303, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQt7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelNo)
                    .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(605, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(209, 209, 209)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchByModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByModelNoActionPerformed
        // TODO add your handling code here:
            boolean record = false;
            String  modelNo = txtModelNo.getText();
            DefaultTableModel dtm = (DefaultTableModel)tblQt7.getModel();
            dtm.setRowCount(0);
            for(Airplane p :aircat.getAirplaneCatalog())
            {   if(p.getModelNo().equalsIgnoreCase(modelNo))
            {
                Object[] col = new Object[7];
                col[0] = p.getAirlineName();
                col[1] = p.getManufacturedBy();
                col[2] = p.getManifactureYear();
                col[3] = p.getNumberOfSeats();
                col[4] = p.getAirport();
                col[5] = p.getAvailabe();
                col[6] = p.getCertificateExpired();
                dtm.addRow(col);  
                record = true;
            }   
            }
            if(!record)
            {
            JOptionPane.showMessageDialog(null, "Record not found");
            }
    }//GEN-LAST:event_btnSearchByModelNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchByModelNo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblQt7;
    private javax.swing.JTable tblQt7;
    private javax.swing.JTextField txtModelNo;
    // End of variables declaration//GEN-END:variables
}
