/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Business.AirlineDirectory;
import Business.Airliner;
import Business.TravelAgency;
import UserInterface.ManageTravelAgency.ManageTravelAgencyJPanel;
import java.awt.CardLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Yash
 */
public class TravelAgencyMainJFrame extends javax.swing.JFrame {
    private AirlineDirectory aircat;
    private TravelAgency trav;
    private Airliner air;
    /**
     * Creates new form TravelAgencyMainJFrame
     */
    public TravelAgencyMainJFrame() {
        initComponents();
        aircat = new AirlineDirectory();
        trav = new TravelAgency();
        air = new Airliner();
        //this.aircat = new AirlineDirectory();
//                String filename = "src\\Business\\AirlineDirectory.csv";
//         File file = new File(filename);
//        try {
//            Scanner inputStream = new Scanner(file);
//            while(inputStream.hasNext())
//            {
//                String data = inputStream.next();
//                String[] values = data.split(",");
//                
//                //System.out.println(data);
//                plane = aircat.addAirliner();
//                
//                //System.out.println(values[0]);
//                plane.setSerialNo(Integer.parseInt(values[0]));
//                plane. setAirlineNo(values[1]);
//                plane.setAirlinerName(values[2]);
//                plane.setDate(values[3]);
//                plane.setTime(values[4]);
//                plane.setNumberOfSeats(Integer.parseInt(values[5]));
//                plane.setSourceAirport(values[6]);
//                plane.setDestinationAirport(values[7]);
//                
//            }
//            inputStream.close();
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(ManageTravelAgencyJPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnTravelAgency = new javax.swing.JButton();
        CardSequenceJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTravelAgency.setText("TRAVEL AGENCY");
        btnTravelAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelAgencyActionPerformed(evt);
            }
        });
        jPanel1.add(btnTravelAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 260, 80));

        jSplitPane1.setLeftComponent(jPanel1);

        CardSequenceJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(CardSequenceJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTravelAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelAgencyActionPerformed
        // TODO add your handling code here:
        TravelAgencyWorkAreaJPanel panel = new TravelAgencyWorkAreaJPanel(CardSequenceJPanel,trav.getAircat(),air);
        CardSequenceJPanel.add("TravelAgencyWorkAreaJPanel",panel);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnTravelAgencyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequenceJPanel;
    private javax.swing.JButton btnTravelAgency;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
